# Generated by Django 4.0.2 on 2022-02-01 22:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', cloudinary.models.CloudinaryField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
