# Generated by Django 4.0.2 on 2022-02-01 23:01

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
